### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by code12412f** [tsy19900929/snpeffToMaf#2]
Hello,

Does this tool also work on VCF files that have been annotated with SNPsift? 

I'm using it with a SNPeff and SNPsift annotated VCF file. This is my command. It gives me a Maf file but also the following errors.
perl /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl JMT1-9.anno_somaticStrict.sort.vcf > test.maf

This gives me:
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 185.
Argument "18:134:0.134:20:-48.2396" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 185.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 185.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 186.
Argument "31:138:0.225:20:-100" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 186.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 186.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 187.
Argument "14:68:0.206:20:-34.7853" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 187.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 187.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 188.
Argument "15:93:0.161:20:-60.5661" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 188.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 188.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 189.
Argument "23:110:0.209:20:-44.5066" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 189.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 189.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 190.
Argument "7:24:0.292:20:-10.2153" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 190.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 190.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 191.
Argument "8:50:0.16:20:-34.2018" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 191.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 191.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 192.
Argument "8:21:0.381:20:-46.9751" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 192.
Use of uninitialized value $minAF in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 54, <INFILE> line 192.
Use of uninitialized value $minDP in numeric lt (<) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 51, <INFILE> line 193.
Argument "39:76:0.513:20:-100" isn't numeric in division (/) at /home/kam9898/snpeffToMaf-master/snpeffToMaf.pl line 53, <INFILE> line 193.

**Comment by tsy19900929** [comment]
Hello，
Yes， It works well.
The errors came frome the FORMAT column，please see [https://github.com/tsy19900929/snpeffToMaf#issues](https://github.com/tsy19900929/snpeffToMaf/blob/master/issues.png)

**Comment by Kekananen** [comment]
The header lines containing 
`##GVCFBlock37-38=minGQ=37(inclusive),maxGQ=38(exclusive)` 
`##GVCFBlock4-5=minGQ=4(inclusive),maxGQ=5(exclusive)` 
throw a long repeating style string of errors when run on a GVCF VCF file.
```
Argument "45,3,0,45,3,45" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "55,6,0,55,6,55" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "0,6,80,6,80,80" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "0,6,64,6,64,64" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "0,6,82,6,82,82" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "0,6,66,6,66,66" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "257,21,0,257,21,257" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "679,63,0,679,63,679" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "0,6,852,69,858,922" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
....
....
Argument "37,0,15,40,20,60" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
Argument "104,0,271,89,164,358,61,175,346,511,113,210,313,320,335" isn't numeric in numeric lt (<) at /home/OSUMC.EDU/kana18/tools/snpeffToMaf/snpeffToMaf.pl line 51, <INFILE> line 0.000000.
```
Would it be possible to simply skip these lines that are not relevant to annotation? I think this might solve the issue unless they are used in conversion and I am unaware? Like the tool idea and it's needed, hope this get's implemented/fixed within the tool itself instead of editing the vcf files.

**Comment by justknowit** [comment]
Hi could you advice a tool to change the format column as indicated in https://github.com/tsy19900929/snpeffToMaf#issues please?

**Comment by master-XS** [comment]
> Hi could you advice a tool to change the format column as indicated in https://github.com/tsy19900929/snpeffToMaf#issues please?

I have the same problem
