### ISSUE TITLE
snpeffToMaff doesn't work on variants greater than one base

### ISSUE THREAD

**Issue by code12412f** [tsy19900929/snpeffToMaf#3]
Hello,

snpeffToMaf doesn't correctly determine the End_Position or the Variant_Type for mutations greater than one base. For example,

Gene     Start_Position     End_Position         Variant_Classification   Variant_Type       Reference_Allele     Tumor_Seq_Allele1  
FLG     152308531        152218985              missense_variant             SNP                     AA                            AA

**Comment by tsy19900929** [comment]
Now，snpeffToMaf only supports the vcf file annotated by snpeff like [https://github.com/tsy19900929/snpeffToMaf/blob/master/yourSampleName.snpeff.vcf](url)

**Comment by code12412f** [comment]
What about variants greater than one base?

**Comment by tsy19900929** [comment]
the new version fixed the issue.
